import { IngredientData } from '@/types';

const ingredientsList: IngredientData[] = [
  {
    name: 'Water', nameRu: 'Вода', category: 'solvent', categoryRu: 'Растворитель',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'neutral',
    tags: ['base'], descriptionRu: 'Основа большинства косметических средств', warningsRu: [], color: 'green',
  },
  {
    name: 'Glycerin', nameRu: 'Глицерин', category: 'humectant', categoryRu: 'Увлажнитель',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'high',
    tags: ['moisturizer'], descriptionRu: 'Мощный увлажнитель, притягивает влагу к коже', warningsRu: [], color: 'green',
  },
  {
    name: 'Butylene Glycol', nameRu: 'Бутиленгликоль', category: 'humectant', categoryRu: 'Увлажнитель',
    comedogenicity: 1, irritation: 0, allergenicity: false, effectiveness: 'medium',
    tags: ['moisturizer'], descriptionRu: 'Увлажнитель и растворитель, улучшает текстуру', warningsRu: [], color: 'green',
  },
  {
    name: 'Niacinamide', nameRu: 'Ниацинамид', category: 'active', categoryRu: 'Актив',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'high',
    tags: ['niacinamide', 'brightening', 'anti_aging', 'pore_minimizer'],
    descriptionRu: 'Витамин B3 — сужает поры, выравнивает тон, укрепляет барьер', warningsRu: [], color: 'green',
  },
  {
    name: 'Retinol', nameRu: 'Ретинол', category: 'active', categoryRu: 'Актив',
    comedogenicity: 0, irritation: 2, allergenicity: false, effectiveness: 'high',
    tags: ['retinol', 'anti_aging', 'acne_fighter'],
    descriptionRu: 'Витамин A — мощный антивозрастной компонент, борется с акне',
    warningsRu: ['Используйте SPF утром', 'Не сочетайте с кислотами (AHA/BHA)', 'Начинайте с низкой концентрации', 'Не используйте при беременности'], color: 'yellow',
  },
  {
    name: 'Retinal', nameRu: 'Ретиналь', category: 'active', categoryRu: 'Актив',
    comedogenicity: 0, irritation: 2, allergenicity: false, effectiveness: 'high',
    tags: ['retinol', 'anti_aging', 'acne_fighter'],
    descriptionRu: 'Форма витамина A, эффективнее ретинола, мягче третиноина',
    warningsRu: ['Используйте SPF утром', 'Не сочетайте с кислотами', 'Не используйте при беременности'], color: 'yellow',
  },
  {
    name: 'Retinyl Palmitate', nameRu: 'Ретинил пальмитат', category: 'active', categoryRu: 'Актив',
    comedogenicity: 0, irritation: 1, allergenicity: false, effectiveness: 'low',
    tags: ['retinol', 'anti_aging'],
    descriptionRu: 'Мягкая форма витамина A, менее эффективна чем ретинол',
    warningsRu: ['Используйте SPF утром'], color: 'yellow',
  },
  {
    name: 'Ascorbic Acid', nameRu: 'Аскорбиновая кислота', category: 'active', categoryRu: 'Актив',
    comedogenicity: 0, irritation: 1, allergenicity: false, effectiveness: 'high',
    tags: ['vitamin_c', 'antioxidant', 'brightening', 'anti_aging'],
    descriptionRu: 'Чистый витамин C — осветляет, защищает от свободных радикалов',
    warningsRu: ['Используйте SPF утром', 'Нестабилен — храните в тёмном месте', 'Не сочетайте с ниацинамидом в высоких концентрациях'], color: 'green',
  },
  {
    name: 'Ascorbyl Glucoside', nameRu: 'Аскорбил глюкозид', category: 'active', categoryRu: 'Актив',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'medium',
    tags: ['vitamin_c', 'antioxidant', 'brightening'],
    descriptionRu: 'Стабильная форма витамина C, мягче чистой аскорбиновой кислоты', warningsRu: ['Используйте SPF утром'], color: 'green',
  },
  {
    name: 'Sodium Ascorbyl Phosphate', nameRu: 'Натрия аскорбил фосфат', category: 'active', categoryRu: 'Актив',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'medium',
    tags: ['vitamin_c', 'antioxidant', 'brightening'],
    descriptionRu: 'Стабильный водорастворимый витамин C', warningsRu: [], color: 'green',
  },
  {
    name: 'Hyaluronic Acid', nameRu: 'Гиалуроновая кислота', category: 'humectant', categoryRu: 'Увлажнитель',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'high',
    tags: ['moisturizer', 'anti_aging'],
    descriptionRu: 'Удерживает до 1000x своего веса воды, глубоко увлажняет', warningsRu: [], color: 'green',
  },
  {
    name: 'Sodium Hyaluronate', nameRu: 'Гиалуронат натрия', category: 'humectant', categoryRu: 'Увлажнитель',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'high',
    tags: ['moisturizer', 'anti_aging'],
    descriptionRu: 'Соль гиалуроновой кислоты, лучше проникает в кожу', warningsRu: [], color: 'green',
  },
  {
    name: 'Salicylic Acid', nameRu: 'Салициловая кислота', category: 'exfoliant', categoryRu: 'Эксфолиант',
    comedogenicity: 0, irritation: 1, allergenicity: false, effectiveness: 'high',
    tags: ['acids', 'bha', 'acne_fighter', 'pore_minimizer'],
    descriptionRu: 'BHA-кислота — очищает поры, борется с акне, противовоспалительная',
    warningsRu: ['Используйте SPF утром', 'Не сочетайте с ретинолом', 'Может сушить кожу'], color: 'yellow',
  },
  {
    name: 'Glycolic Acid', nameRu: 'Гликолевая кислота', category: 'exfoliant', categoryRu: 'Эксфолиант',
    comedogenicity: 0, irritation: 2, allergenicity: false, effectiveness: 'high',
    tags: ['acids', 'aha', 'brightening', 'anti_aging'],
    descriptionRu: 'AHA-кислота — отшелушивает, выравнивает текстуру и тон',
    warningsRu: ['Обязательно используйте SPF', 'Не сочетайте с ретинолом', 'Может вызвать раздражение у чувствительной кожи'], color: 'yellow',
  },
  {
    name: 'Lactic Acid', nameRu: 'Молочная кислота', category: 'exfoliant', categoryRu: 'Эксфолиант',
    comedogenicity: 0, irritation: 1, allergenicity: false, effectiveness: 'high',
    tags: ['acids', 'aha', 'brightening', 'moisturizer'],
    descriptionRu: 'Мягкая AHA-кислота — отшелушивает и увлажняет одновременно',
    warningsRu: ['Используйте SPF утром', 'Не сочетайте с ретинолом'], color: 'green',
  },
  {
    name: 'Mandelic Acid', nameRu: 'Миндальная кислота', category: 'exfoliant', categoryRu: 'Эксфолиант',
    comedogenicity: 0, irritation: 1, allergenicity: false, effectiveness: 'medium',
    tags: ['acids', 'aha', 'brightening'],
    descriptionRu: 'Самая мягкая AHA — подходит для чувствительной кожи',
    warningsRu: ['Используйте SPF утром'], color: 'green',
  },
  {
    name: 'Azelaic Acid', nameRu: 'Азелаиновая кислота', category: 'active', categoryRu: 'Актив',
    comedogenicity: 0, irritation: 1, allergenicity: false, effectiveness: 'high',
    tags: ['acids', 'brightening', 'acne_fighter', 'rosacea_safe'],
    descriptionRu: 'Борется с акне, розацеа, пигментацией. Безопасна при беременности',
    warningsRu: ['Используйте SPF утром'], color: 'green',
  },
  {
    name: 'Panthenol', nameRu: 'Пантенол', category: 'soothing', categoryRu: 'Успокаивающий',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'high',
    tags: ['soothing', 'moisturizer', 'healing'],
    descriptionRu: 'Провитамин B5 — заживляет, успокаивает, увлажняет', warningsRu: [], color: 'green',
  },
  {
    name: 'Allantoin', nameRu: 'Аллантоин', category: 'soothing', categoryRu: 'Успокаивающий',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'medium',
    tags: ['soothing', 'healing'],
    descriptionRu: 'Успокаивает раздражение, смягчает кожу', warningsRu: [], color: 'green',
  },
  {
    name: 'Centella Asiatica Extract', nameRu: 'Экстракт центеллы азиатской', category: 'soothing', categoryRu: 'Успокаивающий',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'high',
    tags: ['soothing', 'healing', 'anti_aging'],
    descriptionRu: 'Мощный успокаивающий компонент, заживляет и укрепляет барьер', warningsRu: [], color: 'green',
  },
  {
    name: 'Madecassoside', nameRu: 'Мадекассозид', category: 'soothing', categoryRu: 'Успокаивающий',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'high',
    tags: ['soothing', 'healing'],
    descriptionRu: 'Активный компонент центеллы, мощное заживление', warningsRu: [], color: 'green',
  },
  {
    name: 'Tocopherol', nameRu: 'Токоферол (Витамин E)', category: 'antioxidant', categoryRu: 'Антиоксидант',
    comedogenicity: 2, irritation: 0, allergenicity: false, effectiveness: 'high',
    tags: ['antioxidant', 'anti_aging', 'vitamin_e'],
    descriptionRu: 'Витамин E — антиоксидант, защищает от свободных радикалов', warningsRu: [], color: 'green',
  },
  {
    name: 'Tocopheryl Acetate', nameRu: 'Токоферил ацетат', category: 'antioxidant', categoryRu: 'Антиоксидант',
    comedogenicity: 2, irritation: 0, allergenicity: false, effectiveness: 'medium',
    tags: ['antioxidant', 'vitamin_e'],
    descriptionRu: 'Стабильная форма витамина E', warningsRu: [], color: 'green',
  },
  {
    name: 'Ceramide NP', nameRu: 'Керамид NP', category: 'emollient', categoryRu: 'Эмолент',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'high',
    tags: ['ceramides', 'barrier_repair'],
    descriptionRu: 'Восстанавливает липидный барьер кожи', warningsRu: [], color: 'green',
  },
  {
    name: 'Ceramide AP', nameRu: 'Керамид AP', category: 'emollient', categoryRu: 'Эмолент',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'high',
    tags: ['ceramides', 'barrier_repair'],
    descriptionRu: 'Укрепляет защитный барьер кожи', warningsRu: [], color: 'green',
  },
  {
    name: 'Ceramide EOP', nameRu: 'Керамид EOP', category: 'emollient', categoryRu: 'Эмолент',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'high',
    tags: ['ceramides', 'barrier_repair'],
    descriptionRu: 'Важный компонент для здорового барьера кожи', warningsRu: [], color: 'green',
  },
  {
    name: 'Squalane', nameRu: 'Сквалан', category: 'emollient', categoryRu: 'Эмолент',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'high',
    tags: ['moisturizer', 'emollient'],
    descriptionRu: 'Лёгкое масло, идентичное кожному жиру, отлично увлажняет', warningsRu: [], color: 'green',
  },
  {
    name: 'Dimethicone', nameRu: 'Диметикон', category: 'emollient', categoryRu: 'Эмолент',
    comedogenicity: 1, irritation: 0, allergenicity: false, effectiveness: 'neutral',
    tags: ['silicones', 'emollient'],
    descriptionRu: 'Силикон — создаёт гладкую текстуру, защитный барьер',
    warningsRu: ['Силикон — может не подходить для чувствительной кожи'], color: 'green',
  },
  {
    name: 'Cyclopentasiloxane', nameRu: 'Циклопентасилоксан', category: 'emollient', categoryRu: 'Эмолент',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'neutral',
    tags: ['silicones', 'emollient'],
    descriptionRu: 'Летучий силикон, придаёт шелковистость',
    warningsRu: ['Силикон'], color: 'green',
  },
  {
    name: 'Cyclohexasiloxane', nameRu: 'Циклогексасилоксан', category: 'emollient', categoryRu: 'Эмолент',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'neutral',
    tags: ['silicones'],
    descriptionRu: 'Летучий силикон для текстуры',
    warningsRu: ['Силикон — вопросы к экологичности'], color: 'yellow',
  },
  {
    name: 'Parfum', nameRu: 'Парфюмерная композиция', category: 'fragrance', categoryRu: 'Отдушка',
    comedogenicity: 0, irritation: 2, allergenicity: true, effectiveness: 'neutral',
    tags: ['fragrance', 'allergen'],
    descriptionRu: 'Отдушка — может содержать десятки скрытых компонентов',
    warningsRu: ['Потенциальный аллерген', 'Может раздражать чувствительную кожу', 'Состав не раскрывается полностью'], color: 'red',
  },
  {
    name: 'Fragrance', nameRu: 'Отдушка', category: 'fragrance', categoryRu: 'Отдушка',
    comedogenicity: 0, irritation: 2, allergenicity: true, effectiveness: 'neutral',
    tags: ['fragrance', 'allergen'],
    descriptionRu: 'Отдушка — потенциальный аллерген и раздражитель',
    warningsRu: ['Потенциальный аллерген', 'Не рекомендуется для чувствительной кожи'], color: 'red',
  },
  {
    name: 'Linalool', nameRu: 'Линалоол', category: 'fragrance', categoryRu: 'Отдушка',
    comedogenicity: 0, irritation: 1, allergenicity: true, effectiveness: 'neutral',
    tags: ['fragrance', 'allergen', 'essential_oils'],
    descriptionRu: 'Ароматический компонент, входит в список аллергенов ЕС',
    warningsRu: ['Аллерген по классификации ЕС'], color: 'yellow',
  },
  {
    name: 'Limonene', nameRu: 'Лимонен', category: 'fragrance', categoryRu: 'Отдушка',
    comedogenicity: 0, irritation: 1, allergenicity: true, effectiveness: 'neutral',
    tags: ['fragrance', 'allergen', 'essential_oils'],
    descriptionRu: 'Ароматический компонент, аллерген ЕС',
    warningsRu: ['Аллерген по классификации ЕС'], color: 'yellow',
  },
  {
    name: 'Citronellol', nameRu: 'Цитронеллол', category: 'fragrance', categoryRu: 'Отдушка',
    comedogenicity: 0, irritation: 1, allergenicity: true, effectiveness: 'neutral',
    tags: ['fragrance', 'allergen'],
    descriptionRu: 'Ароматический компонент, аллерген ЕС',
    warningsRu: ['Аллерген по классификации ЕС'], color: 'yellow',
  },
  {
    name: 'Geraniol', nameRu: 'Гераниол', category: 'fragrance', categoryRu: 'Отдушка',
    comedogenicity: 0, irritation: 1, allergenicity: true, effectiveness: 'neutral',
    tags: ['fragrance', 'allergen'],
    descriptionRu: 'Ароматический компонент, аллерген ЕС',
    warningsRu: ['Аллерген по классификации ЕС'], color: 'yellow',
  },
  {
    name: 'Phenoxyethanol', nameRu: 'Феноксиэтанол', category: 'preservative', categoryRu: 'Консервант',
    comedogenicity: 0, irritation: 1, allergenicity: false, effectiveness: 'neutral',
    tags: ['preservative'],
    descriptionRu: 'Популярный консервант, считается безопасным в допустимых концентрациях', warningsRu: [], color: 'green',
  },
  {
    name: 'Ethylhexylglycerin', nameRu: 'Этилгексилглицерин', category: 'preservative', categoryRu: 'Консервант',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'neutral',
    tags: ['preservative'],
    descriptionRu: 'Усилитель консервантов, также смягчает кожу', warningsRu: [], color: 'green',
  },
  {
    name: 'Methylparaben', nameRu: 'Метилпарабен', category: 'preservative', categoryRu: 'Консервант',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'neutral',
    tags: ['preservative', 'parabens'],
    descriptionRu: 'Парабен — эффективный консервант, споры о безопасности',
    warningsRu: ['Парабен — есть исследования о потенциальных рисках'], color: 'yellow',
  },
  {
    name: 'Propylparaben', nameRu: 'Пропилпарабен', category: 'preservative', categoryRu: 'Консервант',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'neutral',
    tags: ['preservative', 'parabens'],
    descriptionRu: 'Парабен — запрещён в некоторых странах в высоких концентрациях',
    warningsRu: ['Парабен — есть ограничения по концентрации в ЕС'], color: 'yellow',
  },
  {
    name: 'Butylparaben', nameRu: 'Бутилпарабен', category: 'preservative', categoryRu: 'Консервант',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'neutral',
    tags: ['preservative', 'parabens'],
    descriptionRu: 'Парабен с наибольшим количеством вопросов к безопасности',
    warningsRu: ['Парабен — запрещён в некоторых странах', 'Есть исследования о влиянии на гормоны'], color: 'red',
  },
  {
    name: 'DMDM Hydantoin', nameRu: 'ДМДМ Гидантоин', category: 'preservative', categoryRu: 'Консервант',
    comedogenicity: 0, irritation: 2, allergenicity: true, effectiveness: 'neutral',
    tags: ['preservative', 'formaldehyde_releaser'],
    descriptionRu: 'Высвобождает формальдегид — потенциальный канцероген',
    warningsRu: ['Высвобождает формальдегид', 'Потенциальный аллерген', 'Запрещён в ряде стран'], color: 'red',
  },
  {
    name: 'Imidazolidinyl Urea', nameRu: 'Имидазолидинил мочевина', category: 'preservative', categoryRu: 'Консервант',
    comedogenicity: 0, irritation: 2, allergenicity: true, effectiveness: 'neutral',
    tags: ['preservative', 'formaldehyde_releaser'],
    descriptionRu: 'Высвобождает формальдегид',
    warningsRu: ['Высвобождает формальдегид', 'Аллерген'], color: 'red',
  },
  {
    name: 'Sodium Lauryl Sulfate', nameRu: 'Лаурилсульфат натрия', category: 'surfactant', categoryRu: 'ПАВ',
    comedogenicity: 1, irritation: 3, allergenicity: false, effectiveness: 'neutral',
    tags: ['sls', 'surfactant', 'harsh_cleanser'],
    descriptionRu: 'Агрессивный ПАВ — сильно сушит и раздражает кожу',
    warningsRu: ['Очень агрессивный', 'Сильно сушит кожу', 'Разрушает липидный барьер'], color: 'red',
  },
  {
    name: 'Sodium Laureth Sulfate', nameRu: 'Лауретсульфат натрия', category: 'surfactant', categoryRu: 'ПАВ',
    comedogenicity: 1, irritation: 2, allergenicity: false, effectiveness: 'neutral',
    tags: ['sles', 'surfactant'],
    descriptionRu: 'ПАВ — мягче SLS, но всё равно может раздражать',
    warningsRu: ['Может раздражать чувствительную кожу'], color: 'yellow',
  },
  {
    name: 'Cocamidopropyl Betaine', nameRu: 'Кокамидопропил бетаин', category: 'surfactant', categoryRu: 'ПАВ',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'neutral',
    tags: ['surfactant', 'gentle_cleanser'],
    descriptionRu: 'Мягкий ПАВ из кокосового масла', warningsRu: [], color: 'green',
  },
  {
    name: 'Coco-Glucoside', nameRu: 'Коко-глюкозид', category: 'surfactant', categoryRu: 'ПАВ',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'neutral',
    tags: ['surfactant', 'gentle_cleanser'],
    descriptionRu: 'Очень мягкий ПАВ на растительной основе', warningsRu: [], color: 'green',
  },
  {
    name: 'Alcohol Denat', nameRu: 'Денатурированный спирт', category: 'solvent', categoryRu: 'Растворитель',
    comedogenicity: 0, irritation: 2, allergenicity: false, effectiveness: 'neutral',
    tags: ['alcohol', 'drying'],
    descriptionRu: 'Спирт — сушит кожу, разрушает барьер при высоких концентрациях',
    warningsRu: ['Сушит кожу', 'Разрушает липидный барьер', 'Не рекомендуется для сухой и чувствительной кожи'], color: 'red',
  },
  {
    name: 'Alcohol', nameRu: 'Спирт', category: 'solvent', categoryRu: 'Растворитель',
    comedogenicity: 0, irritation: 2, allergenicity: false, effectiveness: 'neutral',
    tags: ['alcohol', 'drying'],
    descriptionRu: 'Этиловый спирт — сушит кожу',
    warningsRu: ['Сушит кожу', 'Не рекомендуется для сухой кожи'], color: 'red',
  },
  {
    name: 'Isopropyl Alcohol', nameRu: 'Изопропиловый спирт', category: 'solvent', categoryRu: 'Растворитель',
    comedogenicity: 0, irritation: 3, allergenicity: false, effectiveness: 'neutral',
    tags: ['alcohol', 'drying'],
    descriptionRu: 'Очень сушащий спирт',
    warningsRu: ['Крайне сушит кожу', 'Раздражает'], color: 'red',
  },
  {
    name: 'Cetyl Alcohol', nameRu: 'Цетиловый спирт', category: 'emollient', categoryRu: 'Эмолент',
    comedogenicity: 2, irritation: 0, allergenicity: false, effectiveness: 'neutral',
    tags: ['fatty_alcohol', 'emollient'],
    descriptionRu: 'Жирный спирт — НЕ сушит, смягчает и стабилизирует', warningsRu: [], color: 'green',
  },
  {
    name: 'Cetearyl Alcohol', nameRu: 'Цетеариловый спирт', category: 'emollient', categoryRu: 'Эмолент',
    comedogenicity: 2, irritation: 0, allergenicity: false, effectiveness: 'neutral',
    tags: ['fatty_alcohol', 'emollient'],
    descriptionRu: 'Жирный спирт — смягчает, стабилизирует текстуру', warningsRu: [], color: 'green',
  },
  {
    name: 'Stearyl Alcohol', nameRu: 'Стеариловый спирт', category: 'emollient', categoryRu: 'Эмолент',
    comedogenicity: 2, irritation: 0, allergenicity: false, effectiveness: 'neutral',
    tags: ['fatty_alcohol', 'emollient'],
    descriptionRu: 'Жирный спирт, смягчает кожу', warningsRu: [], color: 'green',
  },
  {
    name: 'Isopropyl Myristate', nameRu: 'Изопропилмиристат', category: 'emollient', categoryRu: 'Эмолент',
    comedogenicity: 5, irritation: 0, allergenicity: false, effectiveness: 'neutral',
    tags: ['comedogenic', 'emollient'],
    descriptionRu: 'Сильно комедогенный компонент — забивает поры',
    warningsRu: ['Высокая комедогенность (5/5)', 'Не рекомендуется при акне'], color: 'red',
  },
  {
    name: 'Isopropyl Palmitate', nameRu: 'Изопропилпальмитат', category: 'emollient', categoryRu: 'Эмолент',
    comedogenicity: 4, irritation: 0, allergenicity: false, effectiveness: 'neutral',
    tags: ['comedogenic', 'emollient'],
    descriptionRu: 'Комедогенный эмолент — может забивать поры',
    warningsRu: ['Высокая комедогенность (4/5)'], color: 'red',
  },
  {
    name: 'Coconut Oil', nameRu: 'Кокосовое масло', category: 'emollient', categoryRu: 'Эмолент',
    comedogenicity: 4, irritation: 0, allergenicity: false, effectiveness: 'medium',
    tags: ['comedogenic', 'emollient', 'natural'],
    descriptionRu: 'Питательное масло, но сильно комедогенное',
    warningsRu: ['Высокая комедогенность (4/5)', 'Не рекомендуется для жирной кожи'], color: 'yellow',
  },
  {
    name: 'Cocos Nucifera Oil', nameRu: 'Масло кокоса', category: 'emollient', categoryRu: 'Эмолент',
    comedogenicity: 4, irritation: 0, allergenicity: false, effectiveness: 'medium',
    tags: ['comedogenic', 'emollient', 'natural'],
    descriptionRu: 'Кокосовое масло — питает, но забивает поры',
    warningsRu: ['Высокая комедогенность (4/5)'], color: 'yellow',
  },
  {
    name: 'Jojoba Oil', nameRu: 'Масло жожоба', category: 'emollient', categoryRu: 'Эмолент',
    comedogenicity: 2, irritation: 0, allergenicity: false, effectiveness: 'medium',
    tags: ['emollient', 'natural'],
    descriptionRu: 'Лёгкое масло, близкое к кожному себуму', warningsRu: [], color: 'green',
  },
  {
    name: 'Simmondsia Chinensis Seed Oil', nameRu: 'Масло жожоба', category: 'emollient', categoryRu: 'Эмолент',
    comedogenicity: 2, irritation: 0, allergenicity: false, effectiveness: 'medium',
    tags: ['emollient', 'natural'],
    descriptionRu: 'Масло жожоба — увлажняет, не забивает поры', warningsRu: [], color: 'green',
  },
  {
    name: 'Argan Oil', nameRu: 'Аргановое масло', category: 'emollient', categoryRu: 'Эмолент',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'medium',
    tags: ['emollient', 'natural', 'anti_aging'],
    descriptionRu: 'Легкое питательное масло, богато витамином E', warningsRu: [], color: 'green',
  },
  {
    name: 'Argania Spinosa Kernel Oil', nameRu: 'Масло арганы', category: 'emollient', categoryRu: 'Эмолент',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'medium',
    tags: ['emollient', 'natural'],
    descriptionRu: 'Аргановое масло — питает и смягчает', warningsRu: [], color: 'green',
  },
  {
    name: 'Shea Butter', nameRu: 'Масло ши', category: 'occlusive', categoryRu: 'Окклюзив',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'medium',
    tags: ['emollient', 'natural', 'barrier_repair'],
    descriptionRu: 'Богатое питательное масло, восстанавливает барьер', warningsRu: [], color: 'green',
  },
  {
    name: 'Butyrospermum Parkii Butter', nameRu: 'Масло ши (карите)', category: 'occlusive', categoryRu: 'Окклюзив',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'medium',
    tags: ['emollient', 'natural'],
    descriptionRu: 'Масло ши — глубоко питает и защищает', warningsRu: [], color: 'green',
  },
  {
    name: 'Mineral Oil', nameRu: 'Минеральное масло', category: 'occlusive', categoryRu: 'Окклюзив',
    comedogenicity: 2, irritation: 0, allergenicity: false, effectiveness: 'low',
    tags: ['occlusive', 'comedogenic'],
    descriptionRu: 'Продукт нефтепереработки, создаёт плёнку на коже',
    warningsRu: ['Может забивать поры', 'Не даёт коже дышать'], color: 'yellow',
  },
  {
    name: 'Paraffinum Liquidum', nameRu: 'Жидкий парафин', category: 'occlusive', categoryRu: 'Окклюзив',
    comedogenicity: 2, irritation: 0, allergenicity: false, effectiveness: 'low',
    tags: ['occlusive', 'mineral_oil'],
    descriptionRu: 'Минеральное масло — создаёт окклюзивный слой',
    warningsRu: ['Может забивать поры'], color: 'yellow',
  },
  {
    name: 'Petrolatum', nameRu: 'Вазелин', category: 'occlusive', categoryRu: 'Окклюзив',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'medium',
    tags: ['occlusive'],
    descriptionRu: 'Отличный окклюзив, запирает влагу, безопасен', warningsRu: [], color: 'green',
  },
  {
    name: 'Lanolin', nameRu: 'Ланолин', category: 'emollient', categoryRu: 'Эмолент',
    comedogenicity: 1, irritation: 0, allergenicity: true, effectiveness: 'medium',
    tags: ['emollient', 'allergen'],
    descriptionRu: 'Животный воск — хорошо увлажняет, но может вызвать аллергию',
    warningsRu: ['Потенциальный аллерген', 'Животное происхождение'], color: 'yellow',
  },
  {
    name: 'Propylene Glycol', nameRu: 'Пропиленгликоль', category: 'humectant', categoryRu: 'Увлажнитель',
    comedogenicity: 0, irritation: 1, allergenicity: false, effectiveness: 'medium',
    tags: ['humectant', 'penetration_enhancer'],
    descriptionRu: 'Увлажнитель и проводник для других компонентов',
    warningsRu: ['Может раздражать чувствительную кожу'], color: 'green',
  },
  {
    name: 'Carbomer', nameRu: 'Карбомер', category: 'thickener', categoryRu: 'Загуститель',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'neutral',
    tags: ['thickener'],
    descriptionRu: 'Загуститель, создаёт гелевую текстуру', warningsRu: [], color: 'green',
  },
  {
    name: 'Xanthan Gum', nameRu: 'Ксантановая камедь', category: 'thickener', categoryRu: 'Загуститель',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'neutral',
    tags: ['thickener', 'natural'],
    descriptionRu: 'Натуральный загуститель и стабилизатор', warningsRu: [], color: 'green',
  },
  {
    name: 'Stearic Acid', nameRu: 'Стеариновая кислота', category: 'emulsifier', categoryRu: 'Эмульгатор',
    comedogenicity: 2, irritation: 0, allergenicity: false, effectiveness: 'neutral',
    tags: ['emulsifier', 'fatty_acid'],
    descriptionRu: 'Жирная кислота, стабилизатор эмульсий', warningsRu: [], color: 'green',
  },
  {
    name: 'Palmitic Acid', nameRu: 'Пальмитиновая кислота', category: 'emulsifier', categoryRu: 'Эмульгатор',
    comedogenicity: 2, irritation: 0, allergenicity: false, effectiveness: 'neutral',
    tags: ['fatty_acid'],
    descriptionRu: 'Жирная кислота, смягчает кожу', warningsRu: [], color: 'green',
  },
  {
    name: 'Ceteareth-20', nameRu: 'Цетеарет-20', category: 'emulsifier', categoryRu: 'Эмульгатор',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'neutral',
    tags: ['emulsifier', 'peg'],
    descriptionRu: 'Эмульгатор — соединяет масло и воду', warningsRu: [], color: 'green',
  },
  {
    name: 'Polysorbate 20', nameRu: 'Полисорбат 20', category: 'emulsifier', categoryRu: 'Эмульгатор',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'neutral',
    tags: ['emulsifier'],
    descriptionRu: 'Мягкий эмульгатор', warningsRu: [], color: 'green',
  },
  {
    name: 'Polysorbate 80', nameRu: 'Полисорбат 80', category: 'emulsifier', categoryRu: 'Эмульгатор',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'neutral',
    tags: ['emulsifier'],
    descriptionRu: 'Эмульгатор и солюбилизатор', warningsRu: [], color: 'green',
  },
  {
    name: 'Citric Acid', nameRu: 'Лимонная кислота', category: 'ph_adjuster', categoryRu: 'Регулятор pH',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'neutral',
    tags: ['ph_adjuster'],
    descriptionRu: 'Регулирует кислотность средства', warningsRu: [], color: 'green',
  },
  {
    name: 'Sodium Hydroxide', nameRu: 'Гидроксид натрия', category: 'ph_adjuster', categoryRu: 'Регулятор pH',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'neutral',
    tags: ['ph_adjuster'],
    descriptionRu: 'Регулятор pH, в косметике используется в безопасных концентрациях', warningsRu: [], color: 'green',
  },
  {
    name: 'Triethanolamine', nameRu: 'Триэтаноламин', category: 'ph_adjuster', categoryRu: 'Регулятор pH',
    comedogenicity: 0, irritation: 1, allergenicity: false, effectiveness: 'neutral',
    tags: ['ph_adjuster'],
    descriptionRu: 'Регулятор pH и эмульгатор',
    warningsRu: ['В высоких концентрациях может раздражать'], color: 'yellow',
  },
  {
    name: 'Disodium EDTA', nameRu: 'Динатрий ЭДТА', category: 'chelating', categoryRu: 'Хелатирующий агент',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'neutral',
    tags: ['chelating'],
    descriptionRu: 'Связывает ионы металлов, повышает стабильность формулы', warningsRu: [], color: 'green',
  },
  {
    name: 'BHT', nameRu: 'Бутилгидрокситолуол', category: 'antioxidant', categoryRu: 'Антиоксидант',
    comedogenicity: 0, irritation: 1, allergenicity: true, effectiveness: 'neutral',
    tags: ['preservative', 'antioxidant'],
    descriptionRu: 'Синтетический антиоксидант, споры о безопасности',
    warningsRu: ['Потенциальный аллерген', 'Есть вопросы к безопасности при длительном использовании'], color: 'yellow',
  },
  {
    name: 'Urea', nameRu: 'Мочевина', category: 'humectant', categoryRu: 'Увлажнитель',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'high',
    tags: ['humectant', 'exfoliant', 'moisturizer'],
    descriptionRu: 'Мощный увлажнитель, в высоких концентрациях — кератолитик', warningsRu: [], color: 'green',
  },
  {
    name: 'Zinc Oxide', nameRu: 'Оксид цинка', category: 'sunscreen', categoryRu: 'Солнцезащитный',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'high',
    tags: ['spf', 'sunscreen', 'physical_filter', 'soothing'],
    descriptionRu: 'Физический UV-фильтр — защищает от UVA и UVB, успокаивает', warningsRu: [], color: 'green',
  },
  {
    name: 'Titanium Dioxide', nameRu: 'Диоксид титана', category: 'sunscreen', categoryRu: 'Солнцезащитный',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'high',
    tags: ['spf', 'sunscreen', 'physical_filter'],
    descriptionRu: 'Физический UV-фильтр, защищает от UVB и частично UVA', warningsRu: [], color: 'green',
  },
  {
    name: 'Avobenzone', nameRu: 'Авобензон', category: 'sunscreen', categoryRu: 'Солнцезащитный',
    comedogenicity: 0, irritation: 1, allergenicity: false, effectiveness: 'high',
    tags: ['spf', 'sunscreen', 'chemical_filter'],
    descriptionRu: 'Химический UVA-фильтр, может быть нестабильным',
    warningsRu: ['Нестабилен без стабилизирующих фильтров'], color: 'green',
  },
  {
    name: 'Octinoxate', nameRu: 'Октиноксат', category: 'sunscreen', categoryRu: 'Солнцезащитный',
    comedogenicity: 0, irritation: 1, allergenicity: false, effectiveness: 'medium',
    tags: ['spf', 'sunscreen', 'chemical_filter'],
    descriptionRu: 'Химический UVB-фильтр',
    warningsRu: ['Вопросы к влиянию на кораллы и гормоны'], color: 'yellow',
  },
  {
    name: 'Homosalate', nameRu: 'Гомосалат', category: 'sunscreen', categoryRu: 'Солнцезащитный',
    comedogenicity: 0, irritation: 1, allergenicity: false, effectiveness: 'medium',
    tags: ['spf', 'sunscreen', 'chemical_filter'],
    descriptionRu: 'Химический UVB-фильтр',
    warningsRu: ['Есть вопросы к влиянию на эндокринную систему'], color: 'yellow',
  },
  {
    name: 'Aloe Barbadensis Leaf Juice', nameRu: 'Сок алоэ вера', category: 'soothing', categoryRu: 'Успокаивающий',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'medium',
    tags: ['soothing', 'moisturizer', 'natural'],
    descriptionRu: 'Алоэ вера — успокаивает, увлажняет, заживляет', warningsRu: [], color: 'green',
  },
  {
    name: 'Aloe Barbadensis Leaf Extract', nameRu: 'Экстракт алоэ вера', category: 'soothing', categoryRu: 'Успокаивающий',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'medium',
    tags: ['soothing', 'natural'],
    descriptionRu: 'Экстракт алоэ — успокаивает и увлажняет', warningsRu: [], color: 'green',
  },
  {
    name: 'Tea Tree Oil', nameRu: 'Масло чайного дерева', category: 'active', categoryRu: 'Актив',
    comedogenicity: 1, irritation: 2, allergenicity: true, effectiveness: 'medium',
    tags: ['essential_oils', 'acne_fighter', 'antibacterial', 'allergen'],
    descriptionRu: 'Антибактериальное, борется с акне, но может раздражать',
    warningsRu: ['Эфирное масло — потенциальный аллерген', 'Может раздражать чувствительную кожу'], color: 'yellow',
  },
  {
    name: 'Melaleuca Alternifolia Leaf Oil', nameRu: 'Масло чайного дерева', category: 'active', categoryRu: 'Актив',
    comedogenicity: 1, irritation: 2, allergenicity: true, effectiveness: 'medium',
    tags: ['essential_oils', 'acne_fighter', 'allergen'],
    descriptionRu: 'Масло чайного дерева — антисептик',
    warningsRu: ['Эфирное масло — аллерген', 'Не для чувствительной кожи'], color: 'yellow',
  },
  {
    name: 'Lavandula Angustifolia Oil', nameRu: 'Масло лаванды', category: 'fragrance', categoryRu: 'Отдушка',
    comedogenicity: 0, irritation: 2, allergenicity: true, effectiveness: 'low',
    tags: ['essential_oils', 'fragrance', 'allergen'],
    descriptionRu: 'Эфирное масло лаванды — ароматизатор, потенциальный аллерген',
    warningsRu: ['Эфирное масло — аллерген', 'Фототоксичность'], color: 'yellow',
  },
  {
    name: 'Eucalyptus Oil', nameRu: 'Масло эвкалипта', category: 'fragrance', categoryRu: 'Отдушка',
    comedogenicity: 0, irritation: 2, allergenicity: true, effectiveness: 'low',
    tags: ['essential_oils', 'allergen'],
    descriptionRu: 'Эфирное масло — раздражитель и аллерген',
    warningsRu: ['Эфирное масло — аллерген', 'Раздражает кожу'], color: 'red',
  },
  {
    name: 'Camellia Sinensis Leaf Extract', nameRu: 'Экстракт зелёного чая', category: 'antioxidant', categoryRu: 'Антиоксидант',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'high',
    tags: ['antioxidant', 'soothing', 'natural'],
    descriptionRu: 'Мощный антиоксидант, успокаивает воспаления', warningsRu: [], color: 'green',
  },
  {
    name: 'Caffeine', nameRu: 'Кофеин', category: 'active', categoryRu: 'Актив',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'medium',
    tags: ['anti_puffiness', 'antioxidant'],
    descriptionRu: 'Снимает отёчность, антиоксидант, тонизирует', warningsRu: [], color: 'green',
  },
  {
    name: 'Collagen', nameRu: 'Коллаген', category: 'humectant', categoryRu: 'Увлажнитель',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'marketing',
    tags: ['marketing', 'moisturizer'],
    descriptionRu: 'Молекула слишком большая для проникновения в кожу, работает только как увлажнитель на поверхности',
    warningsRu: ['Маркетинговый ингредиент — не проникает в кожу'], color: 'gray',
  },
  {
    name: 'Elastin', nameRu: 'Эластин', category: 'humectant', categoryRu: 'Увлажнитель',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'marketing',
    tags: ['marketing', 'moisturizer'],
    descriptionRu: 'Не проникает в кожу, работает только как плёнкообразователь',
    warningsRu: ['Маркетинговый ингредиент'], color: 'gray',
  },
  {
    name: 'Snail Secretion Filtrate', nameRu: 'Муцин улитки', category: 'active', categoryRu: 'Актив',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'medium',
    tags: ['moisturizer', 'healing', 'anti_aging'],
    descriptionRu: 'Увлажняет, заживляет, содержит гликопротеины и гликозаминогликаны', warningsRu: [], color: 'green',
  },
  {
    name: 'Bakuchiol', nameRu: 'Бакучиол', category: 'active', categoryRu: 'Актив',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'high',
    tags: ['retinol_alternative', 'anti_aging', 'natural'],
    descriptionRu: 'Растительная альтернатива ретинолу, безопасна при беременности', warningsRu: [], color: 'green',
  },
  {
    name: 'Alpha-Arbutin', nameRu: 'Альфа-арбутин', category: 'active', categoryRu: 'Актив',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'high',
    tags: ['brightening', 'anti_pigmentation'],
    descriptionRu: 'Осветляет пигментацию, безопасный и эффективный', warningsRu: [], color: 'green',
  },
  {
    name: 'Arbutin', nameRu: 'Арбутин', category: 'active', categoryRu: 'Актив',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'medium',
    tags: ['brightening', 'anti_pigmentation'],
    descriptionRu: 'Осветляющий компонент, менее эффективен чем альфа-арбутин', warningsRu: [], color: 'green',
  },
  {
    name: 'Kojic Acid', nameRu: 'Койевая кислота', category: 'active', categoryRu: 'Актив',
    comedogenicity: 0, irritation: 1, allergenicity: true, effectiveness: 'high',
    tags: ['brightening', 'anti_pigmentation'],
    descriptionRu: 'Мощный осветлитель пигментации',
    warningsRu: ['Может раздражать чувствительную кожу', 'Используйте SPF'], color: 'yellow',
  },
  {
    name: 'Tranexamic Acid', nameRu: 'Транексамовая кислота', category: 'active', categoryRu: 'Актив',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'high',
    tags: ['brightening', 'anti_pigmentation'],
    descriptionRu: 'Эффективна при мелазме и пигментации, хорошая переносимость', warningsRu: [], color: 'green',
  },
  {
    name: 'Glycyrrhiza Glabra Root Extract', nameRu: 'Экстракт корня солодки', category: 'active', categoryRu: 'Актив',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'medium',
    tags: ['brightening', 'soothing', 'natural'],
    descriptionRu: 'Осветляет, успокаивает, противовоспалительный', warningsRu: [], color: 'green',
  },
  {
    name: 'Palmitoyl Tripeptide-1', nameRu: 'Пальмитоил трипептид-1', category: 'active', categoryRu: 'Актив',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'high',
    tags: ['peptides', 'anti_aging'],
    descriptionRu: 'Пептид — стимулирует выработку коллагена', warningsRu: [], color: 'green',
  },
  {
    name: 'Palmitoyl Tetrapeptide-7', nameRu: 'Пальмитоил тетрапептид-7', category: 'active', categoryRu: 'Актив',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'high',
    tags: ['peptides', 'anti_aging', 'anti_inflammatory'],
    descriptionRu: 'Пептид — противовоспалительный, антивозрастной', warningsRu: [], color: 'green',
  },
  {
    name: 'Acetyl Hexapeptide-8', nameRu: 'Ацетил гексапептид-8', category: 'active', categoryRu: 'Актив',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'medium',
    tags: ['peptides', 'anti_aging'],
    descriptionRu: 'Пептид «Аргирелин» — расслабляет мимические морщины', warningsRu: [], color: 'green',
  },
  {
    name: 'Copper Tripeptide-1', nameRu: 'Медный трипептид-1', category: 'active', categoryRu: 'Актив',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'high',
    tags: ['peptides', 'anti_aging', 'healing'],
    descriptionRu: 'Медный пептид — заживляет, стимулирует коллаген',
    warningsRu: ['Не сочетайте с кислотами и витамином C'], color: 'green',
  },
  {
    name: 'Bentonite', nameRu: 'Бентонит', category: 'thickener', categoryRu: 'Загуститель',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'medium',
    tags: ['clay', 'absorbent'],
    descriptionRu: 'Глина — абсорбирует жир, очищает поры', warningsRu: ['Может сушить кожу'], color: 'green',
  },
  {
    name: 'Kaolin', nameRu: 'Каолин', category: 'thickener', categoryRu: 'Загуститель',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'medium',
    tags: ['clay', 'absorbent'],
    descriptionRu: 'Белая глина — мягко очищает и матирует', warningsRu: [], color: 'green',
  },
  {
    name: 'Sulfur', nameRu: 'Сера', category: 'active', categoryRu: 'Актив',
    comedogenicity: 0, irritation: 1, allergenicity: false, effectiveness: 'medium',
    tags: ['acne_fighter', 'antibacterial'],
    descriptionRu: 'Борется с акне, антибактериальное действие',
    warningsRu: ['Может сушить кожу', 'Имеет специфический запах'], color: 'yellow',
  },
  {
    name: 'Benzoyl Peroxide', nameRu: 'Бензоилпероксид', category: 'active', categoryRu: 'Актив',
    comedogenicity: 0, irritation: 2, allergenicity: false, effectiveness: 'high',
    tags: ['acne_fighter', 'antibacterial'],
    descriptionRu: 'Мощный борец с акне, убивает бактерии',
    warningsRu: ['Сильно сушит кожу', 'Обесцвечивает ткани', 'Не сочетайте с ретинолом', 'Используйте SPF'], color: 'yellow',
  },
  {
    name: 'Adapalene', nameRu: 'Адапален', category: 'active', categoryRu: 'Актив',
    comedogenicity: 0, irritation: 2, allergenicity: false, effectiveness: 'high',
    tags: ['retinol', 'acne_fighter', 'anti_aging'],
    descriptionRu: 'Ретиноид 3-го поколения — борется с акне, антивозрастной',
    warningsRu: ['Используйте SPF', 'Не при беременности', 'Может вызвать шелушение в начале'], color: 'yellow',
  },
  {
    name: 'Rosehip Oil', nameRu: 'Масло шиповника', category: 'emollient', categoryRu: 'Эмолент',
    comedogenicity: 1, irritation: 0, allergenicity: false, effectiveness: 'medium',
    tags: ['natural', 'anti_aging', 'brightening'],
    descriptionRu: 'Богато витамином A и жирными кислотами, выравнивает тон', warningsRu: [], color: 'green',
  },
  {
    name: 'Rosa Canina Seed Oil', nameRu: 'Масло семян шиповника', category: 'emollient', categoryRu: 'Эмолент',
    comedogenicity: 1, irritation: 0, allergenicity: false, effectiveness: 'medium',
    tags: ['natural', 'anti_aging'],
    descriptionRu: 'Масло шиповника — питает и осветляет', warningsRu: [], color: 'green',
  },
  {
    name: 'Witch Hazel', nameRu: 'Гамамелис', category: 'active', categoryRu: 'Актив',
    comedogenicity: 0, irritation: 1, allergenicity: false, effectiveness: 'low',
    tags: ['astringent'],
    descriptionRu: 'Вяжущее средство, сужает поры, но может раздражать',
    warningsRu: ['Часто содержит спирт', 'Может раздражать'], color: 'yellow',
  },
  {
    name: 'Hamamelis Virginiana Water', nameRu: 'Гидролат гамамелиса', category: 'active', categoryRu: 'Актив',
    comedogenicity: 0, irritation: 1, allergenicity: false, effectiveness: 'low',
    tags: ['astringent'],
    descriptionRu: 'Вяжущее, может содержать спирт',
    warningsRu: ['Может раздражать чувствительную кожу'], color: 'yellow',
  },
  {
    name: 'PEG-100 Stearate', nameRu: 'ПЕГ-100 стеарат', category: 'emulsifier', categoryRu: 'Эмульгатор',
    comedogenicity: 1, irritation: 0, allergenicity: false, effectiveness: 'neutral',
    tags: ['peg', 'emulsifier'],
    descriptionRu: 'Эмульгатор на основе ПЕГ', warningsRu: [], color: 'green',
  },
  {
    name: 'Glyceryl Stearate', nameRu: 'Глицерил стеарат', category: 'emulsifier', categoryRu: 'Эмульгатор',
    comedogenicity: 1, irritation: 0, allergenicity: false, effectiveness: 'neutral',
    tags: ['emulsifier'],
    descriptionRu: 'Эмульгатор и смягчитель', warningsRu: [], color: 'green',
  },
  {
    name: 'CI 77891', nameRu: 'Пигмент (диоксид титана)', category: 'colorant', categoryRu: 'Краситель',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'neutral',
    tags: ['colorant'],
    descriptionRu: 'Белый пигмент', warningsRu: [], color: 'green',
  },
  {
    name: 'CI 77491', nameRu: 'Оксид железа (красный)', category: 'colorant', categoryRu: 'Краситель',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'neutral',
    tags: ['colorant'],
    descriptionRu: 'Красный пигмент оксида железа', warningsRu: [], color: 'green',
  },
  {
    name: 'CI 77492', nameRu: 'Оксид железа (жёлтый)', category: 'colorant', categoryRu: 'Краситель',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'neutral',
    tags: ['colorant'],
    descriptionRu: 'Жёлтый пигмент оксида железа', warningsRu: [], color: 'green',
  },
  {
    name: 'CI 77499', nameRu: 'Оксид железа (чёрный)', category: 'colorant', categoryRu: 'Краситель',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'neutral',
    tags: ['colorant'],
    descriptionRu: 'Чёрный пигмент оксида железа', warningsRu: [], color: 'green',
  },
  {
    name: 'Sodium Benzoate', nameRu: 'Бензоат натрия', category: 'preservative', categoryRu: 'Консервант',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'neutral',
    tags: ['preservative'],
    descriptionRu: 'Мягкий консервант', warningsRu: [], color: 'green',
  },
  {
    name: 'Potassium Sorbate', nameRu: 'Сорбат калия', category: 'preservative', categoryRu: 'Консервант',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'neutral',
    tags: ['preservative'],
    descriptionRu: 'Мягкий консервант', warningsRu: [], color: 'green',
  },
  {
    name: 'Dehydroacetic Acid', nameRu: 'Дегидроуксусная кислота', category: 'preservative', categoryRu: 'Консервант',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'neutral',
    tags: ['preservative'],
    descriptionRu: 'Консервант, часто в паре с бензоатом натрия', warningsRu: [], color: 'green',
  },
  {
    name: 'Polyacrylamide', nameRu: 'Полиакриламид', category: 'thickener', categoryRu: 'Загуститель',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'neutral',
    tags: ['thickener', 'film_former'],
    descriptionRu: 'Загуститель и стабилизатор', warningsRu: [], color: 'green',
  },
  {
    name: 'Acrylates/C10-30 Alkyl Acrylate Crosspolymer', nameRu: 'Акрилатный кроссполимер', category: 'thickener', categoryRu: 'Загуститель',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'neutral',
    tags: ['thickener'],
    descriptionRu: 'Загуститель, создаёт гелевую текстуру', warningsRu: [], color: 'green',
  },
  {
    name: 'Hydroxyethylcellulose', nameRu: 'Гидроксиэтилцеллюлоза', category: 'thickener', categoryRu: 'Загуститель',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'neutral',
    tags: ['thickener'],
    descriptionRu: 'Натуральный загуститель', warningsRu: [], color: 'green',
  },
  {
    name: 'Sodium PCA', nameRu: 'ПКН натрия', category: 'humectant', categoryRu: 'Увлажнитель',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'medium',
    tags: ['moisturizer', 'nmf'],
    descriptionRu: 'Компонент натурального увлажняющего фактора кожи (NMF)', warningsRu: [], color: 'green',
  },
  {
    name: 'Trehalose', nameRu: 'Трегалоза', category: 'humectant', categoryRu: 'Увлажнитель',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'medium',
    tags: ['moisturizer'],
    descriptionRu: 'Сахар — увлажняет и защищает клетки от стресса', warningsRu: [], color: 'green',
  },
  {
    name: 'Betaine', nameRu: 'Бетаин', category: 'humectant', categoryRu: 'Увлажнитель',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'medium',
    tags: ['moisturizer'],
    descriptionRu: 'Увлажнитель, осмопротектор', warningsRu: [], color: 'green',
  },
  {
    name: 'Bisabolol', nameRu: 'Бисаболол', category: 'soothing', categoryRu: 'Успокаивающий',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'medium',
    tags: ['soothing', 'anti_inflammatory'],
    descriptionRu: 'Успокаивающий компонент из ромашки', warningsRu: [], color: 'green',
  },
  {
    name: 'Resveratrol', nameRu: 'Ресвератрол', category: 'antioxidant', categoryRu: 'Антиоксидант',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'high',
    tags: ['antioxidant', 'anti_aging'],
    descriptionRu: 'Мощный антиоксидант из красного винограда', warningsRu: [], color: 'green',
  },
  {
    name: 'Ferulic Acid', nameRu: 'Феруловая кислота', category: 'antioxidant', categoryRu: 'Антиоксидант',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'high',
    tags: ['antioxidant', 'anti_aging'],
    descriptionRu: 'Антиоксидант, усиливает действие витаминов C и E', warningsRu: [], color: 'green',
  },
  {
    name: 'Polyhydroxy Acid', nameRu: 'Полигидроксикислота', category: 'exfoliant', categoryRu: 'Эксфолиант',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'medium',
    tags: ['acids', 'pha', 'gentle_exfoliant'],
    descriptionRu: 'Самый мягкий тип кислот, подходит для чувствительной кожи',
    warningsRu: ['Используйте SPF'], color: 'green',
  },
  {
    name: 'Gluconolactone', nameRu: 'Глюконолактон', category: 'exfoliant', categoryRu: 'Эксфолиант',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'medium',
    tags: ['acids', 'pha', 'antioxidant'],
    descriptionRu: 'PHA-кислота — мягкое отшелушивание + антиоксидант', warningsRu: [], color: 'green',
  },
  {
    name: 'Lactobionic Acid', nameRu: 'Лактобионовая кислота', category: 'exfoliant', categoryRu: 'Эксфолиант',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'medium',
    tags: ['acids', 'pha', 'antioxidant', 'moisturizer'],
    descriptionRu: 'PHA-кислота — увлажняет и мягко отшелушивает', warningsRu: [], color: 'green',
  },
  {
    name: 'Trichloroacetic Acid', nameRu: 'Трихлоруксусная кислота', category: 'exfoliant', categoryRu: 'Эксфолиант',
    comedogenicity: 0, irritation: 3, allergenicity: false, effectiveness: 'high',
    tags: ['acids', 'professional_only'],
    descriptionRu: 'Сильная кислота для профессионального пилинга',
    warningsRu: ['Только для профессионального использования', 'Обязателен SPF'], color: 'red',
  },
  {
    name: 'Hydroquinone', nameRu: 'Гидрохинон', category: 'active', categoryRu: 'Актив',
    comedogenicity: 0, irritation: 2, allergenicity: true, effectiveness: 'high',
    tags: ['brightening', 'anti_pigmentation', 'restricted'],
    descriptionRu: 'Мощный осветлитель, но с рисками — запрещён в ЕС в безрецептурных средствах',
    warningsRu: ['Запрещён в ЕС без рецепта', 'Может вызвать охроноз при длительном использовании', 'Обязателен SPF'], color: 'red',
  },
  {
    name: 'Sodium Chloride', nameRu: 'Хлорид натрия', category: 'thickener', categoryRu: 'Загуститель',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'neutral',
    tags: ['thickener'],
    descriptionRu: 'Поваренная соль — загуститель в шампунях', warningsRu: [], color: 'green',
  },
  {
    name: 'Caprylic/Capric Triglyceride', nameRu: 'Каприлик/каприк триглицерид', category: 'emollient', categoryRu: 'Эмолент',
    comedogenicity: 1, irritation: 0, allergenicity: false, effectiveness: 'neutral',
    tags: ['emollient'],
    descriptionRu: 'Лёгкий эмолент из кокосового масла', warningsRu: [], color: 'green',
  },
  {
    name: 'Cetyl Palmitate', nameRu: 'Цетил пальмитат', category: 'emollient', categoryRu: 'Эмолент',
    comedogenicity: 2, irritation: 0, allergenicity: false, effectiveness: 'neutral',
    tags: ['emollient'],
    descriptionRu: 'Воскообразный эмолент', warningsRu: [], color: 'green',
  },
  {
    name: 'Isononyl Isononanoate', nameRu: 'Изононил изононаноат', category: 'emollient', categoryRu: 'Эмолент',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'neutral',
    tags: ['emollient'],
    descriptionRu: 'Лёгкий сухой эмолент', warningsRu: [], color: 'green',
  },
  {
    name: 'Cera Alba', nameRu: 'Пчелиный воск', category: 'occlusive', categoryRu: 'Окклюзив',
    comedogenicity: 2, irritation: 0, allergenicity: true, effectiveness: 'neutral',
    tags: ['occlusive', 'natural'],
    descriptionRu: 'Натуральный воск — защитная плёнка',
    warningsRu: ['Не подходит веганам', 'Потенциальный аллерген'], color: 'yellow',
  },
  {
    name: 'Ricinus Communis Seed Oil', nameRu: 'Касторовое масло', category: 'emollient', categoryRu: 'Эмолент',
    comedogenicity: 1, irritation: 0, allergenicity: false, effectiveness: 'medium',
    tags: ['natural', 'emollient'],
    descriptionRu: 'Касторовое масло — смягчает и увлажняет', warningsRu: [], color: 'green',
  },
  {
    name: 'Helianthus Annuus Seed Oil', nameRu: 'Подсолнечное масло', category: 'emollient', categoryRu: 'Эмолент',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'medium',
    tags: ['natural', 'emollient', 'barrier_repair'],
    descriptionRu: 'Богато линолевой кислотой, восстанавливает барьер', warningsRu: [], color: 'green',
  },
  {
    name: 'Olea Europaea Fruit Oil', nameRu: 'Оливковое масло', category: 'emollient', categoryRu: 'Эмолент',
    comedogenicity: 2, irritation: 0, allergenicity: false, effectiveness: 'medium',
    tags: ['natural', 'emollient'],
    descriptionRu: 'Оливковое масло — питает, но может забивать поры',
    warningsRu: ['Умеренная комедогенность'], color: 'yellow',
  },
  {
    name: 'Tocopheryl Linoleate', nameRu: 'Токоферил линолеат', category: 'antioxidant', categoryRu: 'Антиоксидант',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'medium',
    tags: ['antioxidant', 'vitamin_e'],
    descriptionRu: 'Форма витамина E с линолевой кислотой', warningsRu: [], color: 'green',
  },
  {
    name: 'Ascorbyl Tetraisopalmitate', nameRu: 'Аскорбил тетраизопальмитат', category: 'active', categoryRu: 'Актив',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'medium',
    tags: ['vitamin_c', 'antioxidant'],
    descriptionRu: 'Масляная стабильная форма витамина C', warningsRu: [], color: 'green',
  },
  {
    name: 'Ethylhexyl Methoxycinnamate', nameRu: 'Этилгексил метоксициннамат', category: 'sunscreen', categoryRu: 'Солнцезащитный',
    comedogenicity: 0, irritation: 1, allergenicity: false, effectiveness: 'medium',
    tags: ['spf', 'sunscreen', 'chemical_filter'],
    descriptionRu: 'Химический UVB-фильтр',
    warningsRu: ['Вопросы к влиянию на гормоны'], color: 'yellow',
  },
  {
    name: 'Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine', nameRu: 'Тиносорб S', category: 'sunscreen', categoryRu: 'Солнцезащитный',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'high',
    tags: ['spf', 'sunscreen', 'chemical_filter'],
    descriptionRu: 'Современный широкого спектра UV-фильтр, фотостабильный', warningsRu: [], color: 'green',
  },
  {
    name: 'Ethylhexyl Triazone', nameRu: 'Увинул Т150', category: 'sunscreen', categoryRu: 'Солнцезащитный',
    comedogenicity: 0, irritation: 0, allergenicity: false, effectiveness: 'high',
    tags: ['spf', 'sunscreen', 'chemical_filter'],
    descriptionRu: 'Фотостабильный UVB-фильтр', warningsRu: [], color: 'green',
  },
];

const aliasMap: Record<string, string> = {
  'aqua': 'water',
  'eau': 'water',
  'вода': 'water',
  'глицерин': 'glycerin',
  'ретинол': 'retinol',
  'ниацинамид': 'niacinamide',
  'пантенол': 'panthenol',
  'мочевина': 'urea',
  'кофеин': 'caffeine',
  'коллаген': 'collagen',
  'эластин': 'elastin',
  'сера': 'sulfur',
  'спирт': 'alcohol',
  'сквалан': 'squalane',
  'аллантоин': 'allantoin',
  'бисаболол': 'bisabolol',
  'бакучиол': 'bakuchiol',
  'бетаин': 'betaine',
  'ресвератрол': 'resveratrol',
  'трегалоза': 'trehalose',
  'арбутин': 'arbutin',
  'бензоилпероксид': 'benzoyl peroxide',
  'адапален': 'adapalene',
  'coconut oil': 'cocos nucifera oil',
  'shea butter': 'butyrospermum parkii butter',
  'jojoba oil': 'simmondsia chinensis seed oil',
  'argan oil': 'argania spinosa kernel oil',
  'rosehip oil': 'rosa canina seed oil',
  'tea tree oil': 'melaleuca alternifolia leaf oil',
  'witch hazel': 'hamamelis virginiana water',
  'green tea extract': 'camellia sinensis leaf extract',
  'licorice root extract': 'glycyrrhiza glabra root extract',
  'aloe vera': 'aloe barbadensis leaf juice',
  'centella asiatica': 'centella asiatica extract',
  'vitamin c': 'ascorbic acid',
  'vitamin e': 'tocopherol',
  'vitamin b3': 'niacinamide',
  'vitamin b5': 'panthenol',
  'vitamin a': 'retinol',
  'sls': 'sodium lauryl sulfate',
  'sles': 'sodium laureth sulfate',
};

const databaseMap = new Map<string, IngredientData>();

ingredientsList.forEach(item => {
  databaseMap.set(item.name.toLowerCase(), item);
});

Object.entries(aliasMap).forEach(([alias, canonical]) => {
  const item = databaseMap.get(canonical);
  if (item) {
    databaseMap.set(alias.toLowerCase(), item);
  }
});

export function lookupIngredient(name: string): IngredientData | null {
  const normalized = name.trim().toLowerCase().replace(/\s+/g, ' ');
  if (databaseMap.has(normalized)) {
    return databaseMap.get(normalized) ?? null;
  }

  for (const [key, value] of databaseMap.entries()) {
    if (key.includes(normalized) || normalized.includes(key)) {
      return value;
    }
  }
  return null;
}

export function getIngredientCount(): number {
  return ingredientsList.length;
}
